Deploy Etiquette section
NDCLab/wiki pull request #71
Opened 2021-07-08 19:42 UTC by jessb0t

@georgebuzzell 
Etiquette section (which includes Zenhub page in technical-docs) is ready for official PR! 😄

2021-07-16 22:10 UTC, georgebuzzell requested changes

2021-07-16 22:10 UTC, georgebuzzell commented on docs/etiquette/programming-standards.md
> +---
@F-said and @jessb0t I think this programming standards doc is a really, really great start and good for pushing to main as is. That said, we will want to refine/expand this doc further with additional details and examples to make it easier to understand by novices. but again, no need to hold up pushing to main as is!

2021-07-16 22:11 UTC, georgebuzzell commented
@jessb0t I think this looks really, really, really great! I only have very minor comments/edits. I marked this as "changes requested", but please note that once the minor comments are addressed I am happy to give a quick final approve and merge!!

2021-07-19 14:49 UTC, jessb0t commented on docs/etiquette/naming-conventions.md
> +(Note there are two exceptions to the above branching rules. The first is the wiki, which does not have a `dev` branch, and new branches are created directly off `main` according to the convention `[
Roger!

2021-07-19 15:07 UTC, jessb0t commented on docs/technical-docs/zenhub.md
> +When a new workspace is created, it uses the ZenHub defaults. These are customized for each NDCLab workspace into the following pipelines.
@georgebuzzell The explanation you are looking for is on github-tempates.md as part of the setup of a new project.

For any given instruction, there are two possible locations on the wiki:
1. The technical page that provides a detailed overview of how to interact with the tool.
2. The workflow page that walks someone through a setup.

As you know, I am a strong advocate of avoiding duplications, which means that I was making a case-by-case decision on the best location.  For this particular case, my thought process was this: Most team members will be interacting with ZenHub **after** the pipelines are established.  So the key information for them is what lives in each pipeline and how to work with them (not how to set them up).  Therefore:
- the details of how pipelines should be set up was placed on the "technical" page,
- the instruction to actually match this setup during the creation of a new project was placed on the "workflow" page.

Here on the "technical" page, I attempted to provide a simple indication that the lab customizes the pipelines.  Do you think more clarity is needed?
> When a new workspace is created, it uses the ZenHub defaults. These are customized for each NDCLab workspace into the following pipelines.

2021-07-19 15:17 UTC, jessb0t commented on docs/etiquette/naming-conventions.md
> +* human-friendly (that is, they are descriptive and help us navigate all our projects)
@georgebuzzell I have added BIDS and FAIR!

2021-07-19 15:17 UTC, jessb0t commented
@georgebuzzell All comments above and changes committed addressed.  This is ready for your re-review!

2021-07-19 15:23 UTC, georgebuzzell commented on docs/technical-docs/zenhub.md
> +When a new workspace is created, it uses the ZenHub defaults. These are customized for each NDCLab workspace into the following pipelines.
@jessb0t I think changing "zenhub defaults" to "NDCLab Zenhub defaults" (and making that phrase a link to the technical page with further details would clarify things and also avoid duplication. Agree?

2021-07-19 15:26 UTC, georgebuzzell approved these changes
@jessb0t "approve with mionr revisions" :)

@jessb0t I think changing "zenhub defaults" to "NDCLab Zenhub defaults" (and making that phrase a link to the technical page with further details would clarify things and also avoid duplication. Agree?

2021-07-19 15:31 UTC, jessb0t commented on docs/technical-docs/zenhub.md
> +When a new workspace is created, it uses the ZenHub defaults. These are customized for each NDCLab workspace into the following pipelines.
@georgebuzzell Agree.  Implemented!

2021-07-19 15:36 UTC, merged